name: CI

on:
  push:
    branches:
      - master
    paths:
      - src/**
      - package*.json
      - .eslintrc.json
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
