name: Release Notes

on: workflow_dispatch

permissions:
  contents: read

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          cache: true

      - name: Generate release notes
        run: deno run --allow-env --allow-run --allow-net dev/release-notes.ts >> $GITHUB_STEP_SUMMARY
        env:
          GITHUB_API_URL: ${{ github.api_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
